### PR TITLE
Hints

### LINKED ISSUE #19: Hint
If user does not know the answer, it is possible to click the link and to check the article

### PR DESCRIPTION
**Pull request by erkamguresen**
Displays hints for the questions
closes #19

### CODE REVIEW

**Comment by IrinaSing** [comment]
Hi @erkamguresen, thank you for making hint buttons!

Only right drop-down part of the button works. The left part has CSS respond to click but nothing happen after.  Did you plan some function there too?

**Comment by erkamguresen** [comment]
> Hi @erkamguresen, thank you for making hint buttons!
> 
> Only right drop-down part of the button works. The left part has CSS respond to click but nothing happen after. Did you plan some function there too?

Hi @IrinaSing , I do not plan any function, I just like the view of this collapse button. Is the button confusing?

**Comment by IrinaSing** [comment]
@erkamguresen Yes, a bit. I think if the whole button would be drop-down it would be more clear.

**Comment by erkamguresen** [comment]
@IrinaSing  I changed to a single dropdown button for each hint

**Pull request merged**
